package config

import (
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// template is the starter config.toml written by `pai config init`. It lists the
// settings a new user is most likely to touch, with the built-in defaults made
// explicit, and leaves everything else to the documented defaults so the file
// stays readable. It must remain valid TOML that parses into tomlConfig.
const template = `# PAI configuration — generated by "pai config init".
# Every value below is optional; omit a key to keep its built-in default.
# Inspect the effective settings with "pai config list".

[app]
# provider:model. Built-in providers: deepseek, mistral, openai. Any other name
# with a base_url is treated as an OpenAI-compatible endpoint.
default_model = "deepseek:deepseek-v4-flash"
# A role is data (see "pai role list"); add your own in ~/.config/pai/roles/.
default_role = "devops"
# Stream tokens as they arrive.
streaming = true
# Extended thinking: "low" | "medium" | "high" | "none".
# reasoning = "none"
# Keep the session alive for follow-up input instead of exiting after one task.
# interactive = true

[providers.deepseek]
# Leave empty to use the DEEPSEEK_API_KEY environment variable instead.
api_key = ""

[session]
# Persist every conversation, not just named/nursed ones.
persist = false

[context]
# How much of a single command's output is fed back to the model (bytes), and
# how many lines are kept from its head and tail. The tail is kept on purpose:
# errors and summaries land at the end of command output.
exec_limit   = 8000
search_limit = 8000
head_lines   = 80
tail_lines   = 40

# Compaction of long conversations. The last keep_turns messages are replayed
# in full; older command output is elided to its header so stale results are not
# resent every turn. Nothing is compressed until the conversation exceeds
# elide_after_turns messages; observations smaller than elide_min_bytes are kept.
keep_turns        = 8
elide_after_turns = 16
elide_min_bytes   = 1000
elide_head_lines  = 8

# Second layer, opt-in: once the last prompt exceeded this many tokens, the
# oldest turns are summarized by the model into a single message (in addition to
# the elision above). 0 = disabled. Also available on demand as /compact.
# summarize_after_tokens = 32000

[tool]
# Commands that run without confirmation. An array cannot be set from the CLI —
# edit this file by hand.
# trusted_cmds = ["ls", "cat", "git status"]

# Directories where the file tools (edit, write) need no confirmation — your
# "trusted working place". Also an array, so also hand-edited. A leading ~ is
# expanded; a relative path resolves against the working directory. Empty (the
# default) confirms every edit and write. Prefer an absolute path (e.g.
# "~/work/myproject") over "." so a run from an unexpected directory is not
# silently trusted.
# trusted_paths = ["~/work/myproject"]

# Also require confirmation to read a file outside trusted_paths. Off by
# default: a read changes nothing, but this closes the gap where a file outside
# the workspace is sent to the model without a prompt.
# confirm_read = false

# Seconds after which a single command is killed. 0 (the default) means no
# timeout: Ctrl+C stops a running command, so long builds are not cut off.
# cmd_timeout_seconds = 0
`

// Template returns the starter config.toml contents.
func Template() string { return template }

// WriteTemplate writes the starter config to path. When overwrite is false and
// the file already exists, it makes no change and reports existed=true.
func WriteTemplate(path string, overwrite bool) (existed bool, err error) {
	if _, statErr := os.Stat(path); statErr == nil {
		if !overwrite {
			return true, nil
		}
	} else if !os.IsNotExist(statErr) {
		return false, statErr
	}

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(template), 0600); err != nil {
		return false, err
	}
	return false, nil
}

// ---------------------------------------------------------------------------
// Merge: add only what is missing
// ---------------------------------------------------------------------------

// MergeTemplate writes any template setting that path lacks, leaving every
// existing value untouched. A section that is absent is appended whole (its
// comments included); a missing key in an existing section is inserted at the
// end of that section. Optional settings the template ships commented out are
// added as comments too, so upgrading surfaces new knobs without enabling them.
// Placeholder empties (api_key = "") are not added, so a merge never invents
// empty provider stubs. It returns how many entries it added.
func MergeTemplate(path string) (int, error) {
	lines, err := readLines(path)
	if err != nil {
		return 0, err
	}

	added := 0
	for _, sec := range templateSections() {
		if !hasSection(lines, sec.name) {
			if len(lines) > 0 {
				lines = append(lines, "")
			}
			// trimBlank drops the blank the scanner swept into the section from the
			// template's spacing, so appending it does not double a separator.
			lines = append(lines, trimBlank(sec.lines)...)
			added += len(sec.keys)
			continue
		}
		for _, kv := range sec.keys {
			if hasKey(lines, sec.name, kv.key) {
				continue
			}
			if kv.commented {
				lines = appendBlock(lines, sec.name, kv.insert)
			} else {
				lines = appendKey(lines, sec.name, kv.key, kv.value)
			}
			added++
		}
	}

	if added == 0 {
		return 0, nil
	}
	return added, writeLines(path, lines)
}

// ---------------------------------------------------------------------------
// Reset: back to defaults, but never lose what cannot be recreated
// ---------------------------------------------------------------------------

// ResetTemplate replaces path with the starter template, then restores the
// values a reset must never destroy: provider credentials, the search key, and
// the hand-edited trusted lists (trusted_cmds, trusted_paths) that cannot be set
// from the CLI. Everything else returns to its default.
func ResetTemplate(path string) error {
	raw := preserved(path)

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(template), 0600); err != nil {
		return err
	}

	names := make([]string, 0, len(raw.Providers))
	for name := range raw.Providers {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		pc := raw.Providers[name]
		if pc.APIKey != "" {
			if err := SetScalar(path, "providers."+name, "api_key", strconv.Quote(pc.APIKey)); err != nil {
				return err
			}
		}
		if pc.BaseURL != "" {
			if err := SetScalar(path, "providers."+name, "base_url", strconv.Quote(pc.BaseURL)); err != nil {
				return err
			}
		}
	}
	if raw.Tool.TavilyAPIKey != "" {
		if err := SetScalar(path, "tool", "tavily_api_key", strconv.Quote(raw.Tool.TavilyAPIKey)); err != nil {
			return err
		}
	}
	if len(raw.Tool.TrustedCmds) > 0 {
		if err := SetScalar(path, "tool", "trusted_cmds", arrayLiteral(raw.Tool.TrustedCmds)); err != nil {
			return err
		}
	}
	if len(raw.Tool.TrustedPaths) > 0 {
		if err := SetScalar(path, "tool", "trusted_paths", arrayLiteral(raw.Tool.TrustedPaths)); err != nil {
			return err
		}
	}
	return nil
}

// preserved reads only the file's own values (no environment merging), so a
// reset never writes an environment variable's secret into the config.
func preserved(path string) tomlConfig {
	var raw tomlConfig
	_ = loadTOML(path, &raw)
	return raw
}

func arrayLiteral(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = strconv.Quote(s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// ---------------------------------------------------------------------------
// Template parsing / line helpers
// ---------------------------------------------------------------------------

// templateSection is one [section] of the template, kept verbatim so a merge can
// append it with its comments intact.
type templateSection struct {
	name  string
	lines []string
	keys  []templateKey
}

type templateKey struct {
	key, value string
	// commented marks an example the template ships commented out (an optional
	// setting shown with its explanation). A merge adds it as a comment, never as
	// an active value, so surfacing it changes no behaviour.
	commented bool
	// insert is the exact block to add for a commented key: its explanatory
	// comment lines plus the setting line, verbatim.
	insert []string
}

// templateSections splits the template into sections, extracting each section's
// keys. Active settings carry the value to merge; commented-out examples are kept
// too (flagged commented, with the comment block to insert) so an upgrade can
// surface new optional settings without enabling them. Empty-string placeholders
// are dropped so a merge never invents empty provider stubs.
func templateSections() []templateSection {
	var out []templateSection
	var pending []string // comment/blank lines since the last setting

	for _, line := range strings.Split(template, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			if len(out) > 0 {
				out[len(out)-1].lines = append(out[len(out)-1].lines, line)
				pending = append(pending, line)
			}
			continue
		}
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			out = append(out, templateSection{
				name:  strings.Trim(strings.TrimSpace(trimmed), "[]"),
				lines: []string{line},
			})
			pending = nil
			continue
		}
		if len(out) == 0 {
			continue
		}
		out[len(out)-1].lines = append(out[len(out)-1].lines, line)

		if strings.HasPrefix(trimmed, "#") {
			// A commented-out `key = value` is an optional setting, kept so a merge
			// can add it (as a comment) to a config that predates it.
			if key, value, ok := splitSetting(strings.TrimSpace(strings.TrimPrefix(trimmed, "#"))); ok {
				block := append(append([]string{}, trimBlank(pending)...), line)
				out[len(out)-1].keys = append(out[len(out)-1].keys, templateKey{
					key: key, value: value, commented: true, insert: block,
				})
				pending = nil
				continue
			}
			pending = append(pending, line)
			continue
		}

		if key, value, ok := splitSetting(line); ok && value != `""` {
			out[len(out)-1].keys = append(out[len(out)-1].keys, templateKey{key: key, value: value})
		}
		pending = nil
	}
	return out
}

// trimBlank drops leading and trailing blank lines, so an inserted comment block
// does not carry the blank line that separated it from the block before it.
func trimBlank(lines []string) []string {
	start, end := 0, len(lines)
	for start < end && strings.TrimSpace(lines[start]) == "" {
		start++
	}
	for end > start && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return lines[start:end]
}

// splitSetting parses a `key = value` line, trimming a trailing comment that is
// not inside a quoted string.
func splitSetting(line string) (key, value string, ok bool) {
	idx := strings.Index(line, "=")
	if idx < 0 {
		return "", "", false
	}
	key = strings.TrimSpace(line[:idx])
	if key == "" || strings.ContainsAny(key, ` "'`) {
		return "", "", false
	}
	return key, strings.TrimSpace(stripComment(line[idx+1:])), true
}

// stripComment removes a trailing `# ...` that is outside quotes.
func stripComment(s string) string {
	var quote rune
	for i, r := range s {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			}
		case r == '"' || r == '\'':
			quote = r
		case r == '#':
			return s[:i]
		}
	}
	return s
}

func hasSection(lines []string, section string) bool {
	start, _ := sectionBounds(lines, section)
	return start >= 0
}

func hasKey(lines []string, section, key string) bool {
	start, end := sectionBounds(lines, section)
	if start < 0 {
		return false
	}
	for i := start + 1; i < end; i++ {
		if k, ok := settingKey(lines[i]); ok && k == key {
			return true
		}
	}
	return false
}

// settingKey extracts a setting's key from an active or a commented-out line, so
// a merge does not re-add an example the file already carries.
func settingKey(line string) (string, bool) {
	t := strings.TrimSpace(line)
	t = strings.TrimSpace(strings.TrimPrefix(t, "#"))
	k, _, ok := splitSetting(t)
	if !ok {
		return "", false
	}
	return k, true
}

// appendKey inserts `key = value` at the end of a section (before the next
// header), so merged keys keep the template's order without reversing.
func appendKey(lines []string, section, key, value string) []string {
	return insertAtSectionEnd(lines, section, []string{key + " = " + value})
}

// appendBlock inserts a commented example (its explanation plus the setting line)
// at the end of a section.
func appendBlock(lines []string, section string, block []string) []string {
	return insertAtSectionEnd(lines, section, block)
}

// insertAtSectionEnd splices content before the section's next header, keeping a
// blank line between it and the surrounding content — and before a following
// header — so the merged file stays readable.
func insertAtSectionEnd(lines []string, section string, content []string) []string {
	if len(content) == 0 {
		return lines
	}
	start, end := sectionBounds(lines, section)
	if start < 0 {
		return lines
	}

	out := make([]string, 0, len(lines)+len(content)+2)
	out = append(out, lines[:end]...)
	if end > start+1 && strings.TrimSpace(lines[end-1]) != "" {
		out = append(out, "")
	}
	out = append(out, content...)
	if end < len(lines) && isSectionHeader(lines[end]) {
		out = append(out, "")
	}
	return append(out, lines[end:]...)
}

func isSectionHeader(line string) bool {
	t := strings.TrimSpace(line)
	return strings.HasPrefix(t, "[") && strings.HasSuffix(t, "]")
}
