package config

import (
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// template is the starter config.toml written by `pai config init`. It lists the
// settings a new user is most likely to touch, with the built-in defaults made
// explicit, and leaves everything else to the documented defaults so the file
// stays readable. It must remain valid TOML that parses into tomlConfig.
const template = `# PAI configuration — generated by "pai config init".
# Every value below is optional; omit a key to keep its built-in default.
# Inspect the effective settings with "pai config list".

[app]
# provider:model. Built-in providers: deepseek, mistral, openai. Any other name
# with a base_url is treated as an OpenAI-compatible endpoint.
default_model = "deepseek:deepseek-v4-flash"
# A role is data (see "pai role list"); add your own in ~/.config/pai/roles/.
default_role = "devops"
# Stream tokens as they arrive.
streaming = true
# Extended thinking: "low" | "medium" | "high" | "none".
# reasoning = "none"
# Keep the session alive for follow-up input instead of exiting after one task.
# interactive = true

[providers.deepseek]
# Leave empty to use the DEEPSEEK_API_KEY environment variable instead.
api_key = ""

[session]
# Persist every conversation, not just named/nursed ones.
persist = false

[context]
# How much of a single command's output is fed back to the model (bytes), and
# how many lines are kept from its head and tail. The tail is kept on purpose:
# errors and summaries land at the end of command output.
exec_limit   = 8000
search_limit = 8000
head_lines   = 80
tail_lines   = 40

# Compaction of long conversations. The last keep_turns messages are replayed
# in full; older command output is elided to its header so stale results are not
# resent every turn. Nothing is compressed until the conversation exceeds
# elide_after_turns messages; observations smaller than elide_min_bytes are kept.
keep_turns        = 8
elide_after_turns = 16
elide_min_bytes   = 1000
elide_head_lines  = 8

# Second layer, opt-in: once the last prompt exceeded this many tokens, the
# oldest turns are summarized by the model into a single message (in addition to
# the elision above). 0 = disabled. Also available on demand as /compact.
# summarize_after_tokens = 32000

[tool]
# Commands that run without confirmation. An array cannot be set from the CLI —
# edit this file by hand.
# trusted_cmds = ["ls", "cat", "git status"]
`

// Template returns the starter config.toml contents.
func Template() string { return template }

// WriteTemplate writes the starter config to path. When overwrite is false and
// the file already exists, it makes no change and reports existed=true.
func WriteTemplate(path string, overwrite bool) (existed bool, err error) {
	if _, statErr := os.Stat(path); statErr == nil {
		if !overwrite {
			return true, nil
		}
	} else if !os.IsNotExist(statErr) {
		return false, statErr
	}

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(template), 0600); err != nil {
		return false, err
	}
	return false, nil
}

// ---------------------------------------------------------------------------
// Merge: add only what is missing
// ---------------------------------------------------------------------------

// MergeTemplate writes any template setting that path lacks, leaving every
// existing value untouched. A section that is absent is appended whole (its
// comments included); a missing key in an existing section is inserted at the
// end of that section. Placeholder empties (api_key = "") are not added, so a
// merge never invents empty provider stubs. It returns how many keys it added.
func MergeTemplate(path string) (int, error) {
	lines, err := readLines(path)
	if err != nil {
		return 0, err
	}

	added := 0
	for _, sec := range templateSections() {
		if !hasSection(lines, sec.name) {
			if len(lines) > 0 {
				lines = append(lines, "")
			}
			lines = append(lines, sec.lines...)
			added += len(sec.keys)
			continue
		}
		for _, kv := range sec.keys {
			if hasKey(lines, sec.name, kv.key) {
				continue
			}
			lines = appendKey(lines, sec.name, kv.key, kv.value)
			added++
		}
	}

	if added == 0 {
		return 0, nil
	}
	return added, writeLines(path, lines)
}

// ---------------------------------------------------------------------------
// Reset: back to defaults, but never lose what cannot be recreated
// ---------------------------------------------------------------------------

// ResetTemplate replaces path with the starter template, then restores the
// values a reset must never destroy: provider credentials, the search key, and
// trusted_cmds (an array that cannot be set from the CLI). Everything else
// returns to its default.
func ResetTemplate(path string) error {
	raw := preserved(path)

	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(template), 0600); err != nil {
		return err
	}

	names := make([]string, 0, len(raw.Providers))
	for name := range raw.Providers {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		pc := raw.Providers[name]
		if pc.APIKey != "" {
			if err := SetScalar(path, "providers."+name, "api_key", strconv.Quote(pc.APIKey)); err != nil {
				return err
			}
		}
		if pc.BaseURL != "" {
			if err := SetScalar(path, "providers."+name, "base_url", strconv.Quote(pc.BaseURL)); err != nil {
				return err
			}
		}
	}
	if raw.Tool.TavilyAPIKey != "" {
		if err := SetScalar(path, "tool", "tavily_api_key", strconv.Quote(raw.Tool.TavilyAPIKey)); err != nil {
			return err
		}
	}
	if len(raw.Tool.TrustedCmds) > 0 {
		if err := SetScalar(path, "tool", "trusted_cmds", arrayLiteral(raw.Tool.TrustedCmds)); err != nil {
			return err
		}
	}
	return nil
}

// preserved reads only the file's own values (no environment merging), so a
// reset never writes an environment variable's secret into the config.
func preserved(path string) tomlConfig {
	var raw tomlConfig
	_ = loadTOML(path, &raw)
	return raw
}

func arrayLiteral(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = strconv.Quote(s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// ---------------------------------------------------------------------------
// Template parsing / line helpers
// ---------------------------------------------------------------------------

// templateSection is one [section] of the template, kept verbatim so a merge can
// append it with its comments intact.
type templateSection struct {
	name  string
	lines []string
	keys  []templateKey
}

type templateKey struct{ key, value string }

// templateSections splits the template into sections, extracting each section's
// scalar keys and values. Commented-out settings are ignored, and empty-string
// placeholders are dropped so a merge never adds them.
func templateSections() []templateSection {
	var out []templateSection
	for _, line := range strings.Split(template, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			if len(out) > 0 {
				out[len(out)-1].lines = append(out[len(out)-1].lines, line)
			}
			continue
		}
		if strings.HasPrefix(trimmed, "[") && strings.HasSuffix(trimmed, "]") {
			out = append(out, templateSection{
				name:  strings.Trim(strings.TrimSpace(trimmed), "[]"),
				lines: []string{line},
			})
			continue
		}
		if len(out) == 0 {
			continue
		}
		out[len(out)-1].lines = append(out[len(out)-1].lines, line)
		if key, value, ok := splitSetting(line); ok && value != `""` {
			out[len(out)-1].keys = append(out[len(out)-1].keys, templateKey{key, value})
		}
	}
	return out
}

// splitSetting parses a `key = value` line, trimming a trailing comment that is
// not inside a quoted string.
func splitSetting(line string) (key, value string, ok bool) {
	idx := strings.Index(line, "=")
	if idx < 0 {
		return "", "", false
	}
	key = strings.TrimSpace(line[:idx])
	if key == "" || strings.ContainsAny(key, ` "'`) {
		return "", "", false
	}
	return key, strings.TrimSpace(stripComment(line[idx+1:])), true
}

// stripComment removes a trailing `# ...` that is outside quotes.
func stripComment(s string) string {
	var quote rune
	for i, r := range s {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			}
		case r == '"' || r == '\'':
			quote = r
		case r == '#':
			return s[:i]
		}
	}
	return s
}

func hasSection(lines []string, section string) bool {
	start, _ := sectionBounds(lines, section)
	return start >= 0
}

func hasKey(lines []string, section, key string) bool {
	start, end := sectionBounds(lines, section)
	if start < 0 {
		return false
	}
	for i := start + 1; i < end; i++ {
		if k, _, ok := splitSetting(lines[i]); ok && k == key {
			return true
		}
	}
	return false
}

// appendKey inserts `key = value` at the end of a section (before the next
// header), so merged keys keep the template's order without reversing.
func appendKey(lines []string, section, key, value string) []string {
	_, end := sectionBounds(lines, section)
	out := make([]string, 0, len(lines)+1)
	out = append(out, lines[:end]...)
	out = append(out, key+" = "+value)
	return append(out, lines[end:]...)
}
